export interface Filial {
  franquia: null | any;
  GrupoFilial: null | any;
  Tabela: null | any;
  HandleGrupoFilial: null | any;
  Nome: string;
  Razao: string;
  Fone: string;
  CnpjCpf: string;
  NomeSite: string;
  BackgroudColor: string;
  FontColor: string;
  TitleColor: string;
  Titulo01: null | any;
  Texto01: null | any;
  Titulo02: null | any;
  Texto02: null | any;
  Logo: null | any;
  ValorPedidoMinimo: number;
  Endereco: string;
  Numero: string;
  Complemento: string;
  Bairro: string;
  Cep: string;
  Cidade: string;
  Estado: string;
  NumeroWhatsAppPedido: null | any;
  PrevisaoEntregaMin: number;
  PrevisaoRetiraMin: number;
  TaxaEntrega: number;
  MensagemTaxaEntrega: null | any;
  TipoFrete: string;
  LogoByte: null | any;
  EstaAberto: boolean;
  Titulo01Cardapio: null | any;
  Texto01Cardapio: null | any;
  Titulo02Cardapio: null | any;
  Texto02Cardapio: null | any;
  ApiKeyHere: string;
  ConfigPrecoPizza: null | any;
  PossuiIntegracao: boolean;
  TipoAtendimento: number;
  HandleTabela: null | any;
  Preco: number;
  PossuiValidacaoEndereco: boolean;
  ImagemPadraoPizza: null | any;
  ObrigatorioEnviarPedidoPeloWhatsApp: boolean;
  HandleRamoAtividade: null | any;
  PathRelPedidoSowPublisoft: null | any;
  EmailHost: string;
  EmailUsuario: string;
  EmailSenha: string;
  EmailPorta: number;
  Timeout: number;
  EmailAtivarSsl: boolean;
  MensagemPedidoEmail: string;
  LimiteRetirada: number;
  IntervaloAgendamento: number;
  UtilizaHorarioAgendamento: boolean;
  HandleFranquia: null | any;
  GatewayPagamento: string;
  ChavePublica: string;
  ChaveSecreta: string;
  ImagemPadraoPizzaByte: null | any;
  PathRelPedidoSowPublisoftByte: null | any;
  MostarExcecaoPedidoVenda: boolean;
  LayoutTelaItensSowPublisoft: number;
  PermiteDigitacaoPreco: boolean;
  QuantidadeInteira: boolean;
  DiasPrevisaoEntrega: number;
  QtdAparelhosLiberadosPubliVendas: null | any;
  ChaveApps: string;
  Tabelas: null | any;
  Handle: number;
  HandleFilial: null | any;
  HandleTrade: number;
  Plataforma: number;
}
export interface Grupo1 {
  Codigo: string;
  Nome: string;
  Reduzido: string;
  Tabelas: null | any;
  Handle: number;
  HandleFilial: number;
  HandleTrade: number;
  Plataforma: number;
}
export interface Grupo2 {
  Codigo: string;
  Nome: string;
  Reduzido: string;
  Tipo: string;
  Foto: string;
  PossuiComposicao: boolean;
  PermiteItemSemValor: boolean;
  AbrirTelaExcecoes: boolean;
  PossuiCaracteristicaItem: boolean;
  FotoByte: null | any;
  Tabelas: null | any;
  Handle: number;
  HandleFilial: number;
  HandleTrade: number;
  Plataforma: number;
}
export interface Grupo3 {
  Codigo: string;
  Nome: string;
  Nome2: string;
  Reduzido: string;
  Inativo: boolean;
  QuantidadeItensComposicao: number;
  Tabelas: null | any;
  Handle: number;
  HandleFilial: number;
  HandleTrade: number;
  Plataforma: number;
}
export interface Unidade {
  Sigla: string;
  Descricao: string;
  Tabelas: null | any;
  Handle: number;
  HandleFilial: number;
  HandleTrade: number;
  Plataforma: number;
}
export interface IntItem {
  Filial: Filial;
  Grupo1: Grupo1;
  Grupo2: Grupo2;
  Grupo3: Grupo3;
  Unidade: Unidade;
  HandleGrupo1: number;
  HandleGrupo2: number;
  HandleGrupo3: number;
  HandleUnidade: number;
  ClassificacaoMarketPlace: null | any;
  Codigo: string;
  Descricao: string;
  Complemento: string;
  DescReduzida: null | any;
  Foto: null | any;
  PrecoValor: number;
  Composicao: boolean;
  DescLonga: null | any;
  ComposicaoBarra: string;
  NaoPermiteDesconto: boolean;
  DescricaoDif: null | any;
  VendaValor: number;
  ValorPromocional: null | any;
  VendaFrete: number;
  CustoValor: number;
  Observacao: null | any;
  Quantidade: number;
  FotoByte: null | any;
  Mark: boolean;
  Tabelas: null | any;
  Handle: number;
  HandleFilial: number;
  HandleTrade: number;
  Plataforma: number;
}
export interface IntItemCart {
  Filial: Filial;
  Grupo1: Grupo1;
  Grupo2: Grupo2;
  Grupo3: Grupo3;
  Unidade: Unidade;
  HandleGrupo1: number;
  HandleGrupo2: number;
  HandleGrupo3: number;
  HandleUnidade: number;
  ClassificacaoMarketPlace: null | any;
  Codigo: string;
  Descricao: string;
  Complemento: string;
  DescReduzida: null | any;
  Foto: null | any;
  PrecoValor: number;
  Composicao: boolean;
  DescLonga: null | any;
  ComposicaoBarra: string;
  NaoPermiteDesconto: boolean;
  DescricaoDif: null | any;
  VendaValor: number;
  ValorPromocional: null | any;
  VendaFrete: number;
  CustoValor: number;
  Observacao: null | any;
  Quantidade: number;
  FotoByte: null | any;
  Mark: boolean;
  Tabelas: null | any;
  Handle: number;
  HandleFilial: number;
  HandleTrade: number;
  Plataforma: number;
  Amount: number;
  Total: number;
}
