import Realm from "realm";
import { Tabela } from "./Interface-Tabela";

export interface Filial {
  franquia?: string;
  GrupoFilial?: string;
  Tabela?: Tabela | null;
  HandleGrupoFilial?: string;
  Nome: string;
  Razao?: string;
  Fone?: string;
  CnpjCpf?: string;
  NomeSite?: string;
  BackgroudColor?: string;
  FontColor?: string;
  TitleColor?: string;
  Titulo01?: string;
  Texto01?: string;
  Titulo02?: string;
  Texto02?: string;
  Logo?: string;
  ValorPedidoMinimo?: number;
  Endereco?: string;
  Numero?: string;
  Complemento?: string;
  Bairro?: string;
  Cep?: string;
  Cidade?: string;
  Estado?: string;
  NumeroWhatsAppPedido?: string;
  PrevisaoEntregaMin?: number;
  PrevisaoRetiraMin?: number;
  TaxaEntrega?: number;
  MensagemTaxaEntrega?: string;
  TipoFrete?: string;
  LogoByte?: string;
  EstaAberto?: boolean;
  Titulo01Cardapio?: string;
  Texto01Cardapio?: string;
  Titulo02Cardapio?: string;
  Texto02Cardapio?: string;
  ApiKeyHere?: string;
  ConfigPrecoPizza?: string;
  PossuiIntegracao?: boolean;
  TipoAtendimento?: number;
  HandleTabela?: number;
  Preco?: number;
  PossuiValidacaoEndereco?: boolean;
  ImagemPadraoPizza?: string;
  ObrigatorioEnviarPedidoPeloWhatsApp?: boolean;
  HandleRamoAtividade?: string;
  PathRelPedidoSowPublisoft?: string;
  EmailHost?: string;
  EmailUsuario?: string;
  EmailSenha?: string;
  EmailPorta?: number;
  Timeout?: number;
  EmailAtivarSsl?: boolean;
  MensagemPedidoEmail?: string;
  LimiteRetirada?: number;
  IntervaloAgendamento?: number;
  UtilizaHorarioAgendamento?: boolean;
  HandleFranquia?: number;
  GatewayPagamento?: string;
  ChavePublica?: string;
  ChaveSecreta?: string;
  ImagemPadraoPizzaByte?: string;
  PathRelPedidoSowPublisoftByte?: string;
  MostarExcecaoPedidoVenda?: boolean;
  LayoutTelaItensSowPublisoft?: number;
  PermiteDigitacaoPreco?: boolean;
  QuantidadeInteira?: number;
  DiasPrevisaoEntrega?: number;
  QtdAparelhosLiberadosPubliVendas?: number;
  ChaveApps?: string;
  Tabelas?: string;
  Handle: number;
  HandleFilial?: number;
  HandleTrade?: number;
  Plataforma?: number;
}

export type FilialObject = Filial & Realm.Object;
