import { ObjectSchema } from "realm";

export const SchemaFilial: ObjectSchema = {
  name: "SchemaFilial",
  primaryKey: "Handle",
  properties: {
    franquia: { type: "string", optional: true },
    GrupoFilial: { type: "string", optional: true },
    Tabela: { type: "string", optional: true },
    HandleGrupoFilial: { type: "string", optional: true },
    Nome: { type: "string", indexed: true },
    Razao: { type: "string", optional: true },
    Fone: { type: "string", optional: true },
    CnpjCpf: { type: "string", optional: true },
    NomeSite: { type: "string", optional: true },
    BackgroudColor: { type: "string", optional: true },
    FontColor: { type: "string", optional: true },
    TitleColor: { type: "string", optional: true },
    Titulo01: { type: "string", optional: true },
    Texto01: { type: "string", optional: true },
    Titulo02: { type: "string", optional: true },
    Texto02: { type: "string", optional: true },
    Logo: { type: "string", optional: true },
    ValorPedidoMinimo: { type: "double", optional: true },
    Endereco: { type: "string", optional: true },
    Numero: { type: "string", optional: true },
    Complemento: { type: "string", optional: true },
    Bairro: { type: "string", optional: true },
    Cep: { type: "string", optional: true },
    Cidade: { type: "string", optional: true },
    Estado: { type: "string", optional: true },
    NumeroWhatsAppPedido: { type: "string", optional: true },
    PrevisaoEntregaMin: { type: "int", optional: true },
    PrevisaoRetiraMin: { type: "int", optional: true },
    TaxaEntrega: { type: "double", optional: true },
    MensagemTaxaEntrega: { type: "string", optional: true },
    TipoFrete: { type: "string", optional: true },
    LogoByte: { type: "string", optional: true },
    EstaAberto: { type: "bool", optional: true },
    Titulo01Cardapio: { type: "string", optional: true },
    Texto01Cardapio: { type: "string", optional: true },
    Titulo02Cardapio: { type: "string", optional: true },
    Texto02Cardapio: { type: "string", optional: true },
    ApiKeyHere: { type: "string", optional: true },
    ConfigPrecoPizza: { type: "string", optional: true },
    PossuiIntegracao: { type: "bool", optional: true },
    TipoAtendimento: { type: "int", optional: true },
    HandleTabela: { type: "string", optional: true },
    Preco: { type: "int", optional: true },
    PossuiValidacaoEndereco: { type: "bool", optional: true },
    ImagemPadraoPizza: { type: "string", optional: true },
    ObrigatorioEnviarPedidoPeloWhatsApp: { type: "bool", optional: true },
    HandleRamoAtividade: { type: "string", optional: true },
    PathRelPedidoSowPublisoft: { type: "string", optional: true },
    EmailHost: { type: "string", optional: true },
    EmailUsuario: { type: "string", optional: true },
    EmailSenha: { type: "string", optional: true },
    EmailPorta: { type: "int", optional: true },
    Timeout: { type: "int", optional: true },
    EmailAtivarSsl: { type: "bool", optional: true },
    MensagemPedidoEmail: { type: "string", optional: true },
    LimiteRetirada: { type: "int", optional: true },
    IntervaloAgendamento: { type: "int", optional: true },
    UtilizaHorarioAgendamento: { type: "bool", optional: true },
    HandleFranquia: { type: "string", optional: true },
    GatewayPagamento: { type: "string", optional: true },
    ChavePublica: { type: "string", optional: true },
    ChaveSecreta: { type: "string", optional: true },
    ImagemPadraoPizzaByte: { type: "string", optional: true },
    PathRelPedidoSowPublisoftByte: { type: "string", optional: true },
    MostarExcecaoPedidoVenda: { type: "bool", optional: true },
    LayoutTelaItensSowPublisoft: { type: "int", optional: true },
    PermiteDigitacaoPreco: { type: "bool", optional: true },
    QuantidadeInteira: { type: "bool", optional: true },
    DiasPrevisaoEntrega: { type: "int", optional: true },
    QtdAparelhosLiberadosPubliVendas: { type: "string", optional: true },
    ChaveApps: { type: "string", optional: true },
    Tabelas: { type: "string", optional: true }, //Não é utilizado
    Handle: "int",
    HandleFilial: { type: "string", optional: true },
    HandleTrade: { type: "int", optional: true },
    Plataforma: { type: "int", optional: true },
  },
};
